"""Top-level package for the twopy two-photon imaging analysis tool.

The package exposes project metadata and script-friendly public APIs.
Inputs: none.
Outputs: package constants and helper functions imported by users and scripts.
"""

from twopy._version import __version__
from twopy.analysis import (
    DEFAULT_RESPONSE_POST_WINDOW_SECONDS,
    DEFAULT_RESPONSE_PRE_WINDOW_SECONDS,
    AnalysisResponseComputation,
    AnalysisResponseRun,
    BackgroundCorrectedRoiTraces,
    BackgroundCorrectionMethod,
    CorrelationFilterOptions,
    DeltaFOverFFitMode,
    DeltaFOverFOptions,
    EpochFrameWindow,
    FrameWindow,
    GroupedRoiResponses,
    GroupedRoiResponseSummary,
    InterpolatedEpochMapping,
    LoadedAnalysisOutputs,
    LowPassFilterOptions,
    ResponseProcessingOptions,
    RoiCorrelationScores,
    RoiDeltaFOverF,
    RoiResponseSummary,
    RoiResponseTrial,
    SmoothingOptions,
    WindowedRoiResponse,
    analyze_recording_responses,
    apply_motion_artifact_mask_to_delta_f_over_f,
    compute_recording_responses,
    compute_roi_delta_f_over_f,
    extract_background_corrected_roi_traces,
    frame_windows_from_photodiode_alignment,
    group_delta_f_over_f_by_epoch,
    interpolate_stimulus_epochs_to_frame_windows,
    is_interleave_epoch_name,
    load_analysis_outputs,
    make_frame_windows,
    map_stimulus_epochs_to_frame_windows,
    save_analysis_outputs,
    select_epoch_frame_windows,
    split_traces_by_frame_windows,
    summarize_epoch_roi_responses,
    summarize_grouped_responses,
    write_response_summary_grouped_csv,
    write_response_summary_trials_csv,
)
from twopy.api import find_recordings
from twopy.conversion import convert_recording_to_twopy, load_source_conversion_inputs
from twopy.converted import load_converted_recording, recording_frame_rate_hz
from twopy.napari import (
    NapariControlDocks,
    NapariRecordingView,
    add_twopy_magicgui_controls,
    launch_napari,
    open_recording_in_napari,
    roi_label_image_from_layer,
    save_napari_label_rois,
)
from twopy.photodiode_classification import (
    ClassifiedPhotodiodeEvent,
    ClassifiedStimulusTiming,
    ClassifiedStimulusWindow,
    PhotodiodeDurationClass,
    PhotodiodeEventType,
    classify_recording_photodiode_events,
)
from twopy.roi import (
    RoiSet,
    RoiTraces,
    extract_roi_traces,
    load_roi_set,
    make_roi_set,
    make_roi_set_from_label_image,
    roi_set_to_label_image,
    save_roi_set,
)
from twopy.spatial import SpatialCrop, SpatialDomain, full_frame_crop
from twopy.stimulus import (
    StimulusSpecificColumnMapping,
    default_interleave_epoch_number,
    map_stimulus_specific_column,
    stimulus_epoch_names_by_number,
)
from twopy.synchronization import (
    AlignedPhotodiodeEvent,
    PhotodiodeAlignment,
    PhotodiodeEvent,
    PhotodiodeEventSet,
    detect_photodiode_events,
    detect_recording_photodiode_events,
    pair_photodiode_events_to_imaging_frames,
)

__all__ = [
    "__version__",
    "AlignedPhotodiodeEvent",
    "AnalysisResponseRun",
    "AnalysisResponseComputation",
    "analyze_recording_responses",
    "add_twopy_magicgui_controls",
    "apply_motion_artifact_mask_to_delta_f_over_f",
    "BackgroundCorrectedRoiTraces",
    "BackgroundCorrectionMethod",
    "ClassifiedPhotodiodeEvent",
    "ClassifiedStimulusTiming",
    "ClassifiedStimulusWindow",
    "classify_recording_photodiode_events",
    "compute_roi_delta_f_over_f",
    "compute_recording_responses",
    "CorrelationFilterOptions",
    "convert_recording_to_twopy",
    "DEFAULT_RESPONSE_POST_WINDOW_SECONDS",
    "DEFAULT_RESPONSE_PRE_WINDOW_SECONDS",
    "default_interleave_epoch_number",
    "detect_photodiode_events",
    "detect_recording_photodiode_events",
    "DeltaFOverFFitMode",
    "DeltaFOverFOptions",
    "EpochFrameWindow",
    "extract_background_corrected_roi_traces",
    "extract_roi_traces",
    "find_recordings",
    "frame_windows_from_photodiode_alignment",
    "FrameWindow",
    "full_frame_crop",
    "group_delta_f_over_f_by_epoch",
    "GroupedRoiResponseSummary",
    "GroupedRoiResponses",
    "InterpolatedEpochMapping",
    "interpolate_stimulus_epochs_to_frame_windows",
    "is_interleave_epoch_name",
    "launch_napari",
    "load_analysis_outputs",
    "load_converted_recording",
    "load_roi_set",
    "load_source_conversion_inputs",
    "LoadedAnalysisOutputs",
    "LowPassFilterOptions",
    "make_roi_set_from_label_image",
    "make_frame_windows",
    "make_roi_set",
    "map_stimulus_epochs_to_frame_windows",
    "map_stimulus_specific_column",
    "NapariControlDocks",
    "NapariRecordingView",
    "open_recording_in_napari",
    "pair_photodiode_events_to_imaging_frames",
    "PhotodiodeAlignment",
    "PhotodiodeDurationClass",
    "PhotodiodeEvent",
    "PhotodiodeEventType",
    "PhotodiodeEventSet",
    "ResponseProcessingOptions",
    "recording_frame_rate_hz",
    "RoiDeltaFOverF",
    "RoiCorrelationScores",
    "RoiResponseSummary",
    "RoiResponseTrial",
    "RoiSet",
    "RoiTraces",
    "roi_label_image_from_layer",
    "roi_set_to_label_image",
    "save_analysis_outputs",
    "save_napari_label_rois",
    "save_roi_set",
    "select_epoch_frame_windows",
    "split_traces_by_frame_windows",
    "SmoothingOptions",
    "SpatialCrop",
    "SpatialDomain",
    "StimulusSpecificColumnMapping",
    "stimulus_epoch_names_by_number",
    "summarize_epoch_roi_responses",
    "summarize_grouped_responses",
    "WindowedRoiResponse",
    "write_response_summary_grouped_csv",
    "write_response_summary_trials_csv",
]
