"""Analysis helpers for converted two-photon recordings.

Inputs: converted twopy recordings, ROI traces, photodiode-aligned windows, and
analysis parameters.
Outputs: background-corrected traces and trial/frame-window response objects.

This package is GUI-independent and operates only on twopy-owned converted
files or in-memory objects derived from them.
"""

from twopy.analysis.background_subtraction import (
    BackgroundCorrectedRoiTraces,
    BackgroundCorrectionMethod,
    extract_background_corrected_roi_traces,
)
from twopy.analysis.dff import (
    DeltaFOverFFitMode,
    RoiDeltaFOverF,
    compute_roi_delta_f_over_f,
)
from twopy.analysis.dff_options import DeltaFOverFBaselineMode, DeltaFOverFOptions
from twopy.analysis.group_matching import (
    ManualFovGroupRow,
    ManualRoiMatchGroup,
    ManualRoiMatchRow,
    ManualRoiMatchStatus,
    add_manual_roi_match_group,
    append_manual_roi_match_rows,
    load_manual_fov_group_rows,
    load_manual_roi_match_rows,
    make_manual_fov_group_rows,
    make_manual_roi_match_rows,
    matched_manual_roi_groups,
    next_group_cell_id,
    remove_manual_roi_match_group,
    replace_manual_roi_match_group,
    save_manual_fov_group_rows,
    save_manual_roi_match_rows,
)
from twopy.analysis.kernels import (
    Hemisphere,
    KernelFitMethod,
    KernelStimulusModality,
    RecordingKernelFit,
    StimulusKernelOptions,
    default_kernel_stimulus_column,
    fit_recording_stimulus_kernels,
    fit_stimulus_kernel,
)
from twopy.analysis.motion import apply_motion_artifact_mask_to_delta_f_over_f
from twopy.analysis.persistence import (
    ANALYSIS_OUTPUT_FILE_FORMAT,
    LoadedAnalysisOutputs,
    load_analysis_outputs,
    save_analysis_outputs,
    write_response_summary_grouped_csv,
    write_response_summary_trials_csv,
)
from twopy.analysis.response_context import default_recording_baseline_epoch_number
from twopy.analysis.response_maps import (
    EpochResponseMap,
    ResponseMapData,
    ResponseMapMode,
    ResponseMapOptions,
    compute_recording_response_maps,
    load_response_map_data,
    save_response_map_data,
)
from twopy.analysis.response_plotting import (
    EpochResponsePlotData,
    ResponsePlotData,
    filter_response_plot_data_rois,
    response_plot_data_from_grouped,
    response_plot_window_options_from_grouped,
)
from twopy.analysis.response_processing import (
    CorrelationFilterOptions,
    LowPassFilterOptions,
    ResponseProcessingOptions,
    RoiCorrelationScores,
    SmoothingOptions,
)
from twopy.analysis.responses import (
    GroupedRoiResponses,
    GroupedRoiResponseSummary,
    RoiResponseSummary,
    RoiResponseTrial,
    finite_mean_and_sem,
    group_delta_f_over_f_by_epoch,
    summarize_epoch_roi_responses,
    summarize_grouped_responses,
    validate_grouped_roi_responses,
)
from twopy.analysis.timing import (
    RecordingTiming,
    TimingSource,
    resolve_recording_timing,
)
from twopy.analysis.trials import (
    EpochFrameWindow,
    FrameWindow,
    WindowedRoiResponse,
    default_baseline_epoch_number,
    is_baseline_epoch_name,
    make_frame_windows,
    no_baseline_epoch_frame_windows,
    resolve_baseline_frame_windows,
    select_baseline_frame_windows,
    split_traces_by_frame_windows,
)
from twopy.analysis.workflow import (
    DEFAULT_RESPONSE_POST_WINDOW_SECONDS,
    DEFAULT_RESPONSE_PRE_WINDOW_SECONDS,
    AnalysisResponseComputation,
    AnalysisResponseRun,
    analyze_recording_responses,
    compute_recording_responses,
)

__all__ = [
    "analyze_recording_responses",
    "AnalysisResponseComputation",
    "AnalysisResponseRun",
    "DEFAULT_RESPONSE_POST_WINDOW_SECONDS",
    "DEFAULT_RESPONSE_PRE_WINDOW_SECONDS",
    "apply_motion_artifact_mask_to_delta_f_over_f",
    "ANALYSIS_OUTPUT_FILE_FORMAT",
    "BackgroundCorrectedRoiTraces",
    "BackgroundCorrectionMethod",
    "compute_roi_delta_f_over_f",
    "compute_recording_responses",
    "compute_recording_response_maps",
    "CorrelationFilterOptions",
    "default_baseline_epoch_number",
    "default_recording_baseline_epoch_number",
    "DeltaFOverFBaselineMode",
    "DeltaFOverFOptions",
    "DeltaFOverFFitMode",
    "EpochResponseMap",
    "EpochResponsePlotData",
    "EpochFrameWindow",
    "extract_background_corrected_roi_traces",
    "fit_recording_stimulus_kernels",
    "fit_stimulus_kernel",
    "default_kernel_stimulus_column",
    "Hemisphere",
    "FrameWindow",
    "group_delta_f_over_f_by_epoch",
    "GroupedRoiResponseSummary",
    "GroupedRoiResponses",
    "is_baseline_epoch_name",
    "KernelFitMethod",
    "KernelStimulusModality",
    "load_analysis_outputs",
    "load_response_map_data",
    "LoadedAnalysisOutputs",
    "LowPassFilterOptions",
    "ManualFovGroupRow",
    "ManualRoiMatchGroup",
    "ManualRoiMatchRow",
    "ManualRoiMatchStatus",
    "matched_manual_roi_groups",
    "make_frame_windows",
    "make_manual_fov_group_rows",
    "make_manual_roi_match_rows",
    "no_baseline_epoch_frame_windows",
    "next_group_cell_id",
    "RecordingKernelFit",
    "RecordingTiming",
    "RoiDeltaFOverF",
    "ResponseMapData",
    "ResponseMapMode",
    "ResponseMapOptions",
    "ResponsePlotData",
    "ResponseProcessingOptions",
    "RoiCorrelationScores",
    "RoiResponseSummary",
    "RoiResponseTrial",
    "resolve_baseline_frame_windows",
    "resolve_recording_timing",
    "add_manual_roi_match_group",
    "append_manual_roi_match_rows",
    "load_manual_fov_group_rows",
    "load_manual_roi_match_rows",
    "remove_manual_roi_match_group",
    "replace_manual_roi_match_group",
    "save_analysis_outputs",
    "save_response_map_data",
    "save_manual_fov_group_rows",
    "save_manual_roi_match_rows",
    "select_baseline_frame_windows",
    "finite_mean_and_sem",
    "filter_response_plot_data_rois",
    "split_traces_by_frame_windows",
    "StimulusKernelOptions",
    "SmoothingOptions",
    "response_plot_data_from_grouped",
    "response_plot_window_options_from_grouped",
    "summarize_epoch_roi_responses",
    "summarize_grouped_responses",
    "TimingSource",
    "validate_grouped_roi_responses",
    "WindowedRoiResponse",
    "write_response_summary_grouped_csv",
    "write_response_summary_trials_csv",
]
